### ISSUE TITLE
ERROR: unsatisfiable constraints: eve (missing): required by: world[eve]

### ISSUE THREAD

**Issue by easysun** [Edux87/docker-python-eve#1]
There is an error occupied on step 4 when run the command `docker-compose up`
This is the error message: 
"""
Step 4 : RUN apk add --update musl python3 py-pip eve wget &&     rm /var/cache/apk/*
 ---> Running in d055aff424ab
fetch http://dl-cdn.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  eve (missing):
    required by: world[eve]
ERROR: Service 'api' failed to build: The command '/bin/sh -c apk add --update musl python3 py-pip eve wget &&     rm /var/cache/apk/*' returned a non-zero code: 1
"""

**Comment by EntityB** [comment]
same bug here

**Comment by edgrcas** [comment]
fix ....
